### ISSUE TITLE
How to add to the homekit using the type of television?

### ISSUE THREAD

**Issue by cacherocks** [hobbyquaker/node-red-contrib-lgtv#15]
Could you prepare a ready-made flow for adding a [TV to the HomeKit](https://github.com/KhaosT/HAP-NodeJS/blob/bb0c5b9af02e40b3ee7fc2352eb5ada20b369c68/src/accessories/TV_accessory.ts) via node Homekit “[node-red-contrib-homekit-bridged](https://flows.nodered.org/node/node-red-contrib-homekit-bridged)” using your plugin?

It would be amazing!

**Comment by hobbyquaker** [comment]
I'm not using node-red-contrib-homekit-bridged, so i fear i can't help you with that. Maybe the maintainers of the homekit nodes can?
