### ISSUE TITLE
What is node-red-contrib-lgtv-with-turnon

### ISSUE THREAD

**Issue by bartbutenaers** [hobbyquaker/node-red-contrib-lgtv#28]
Hi Sebastian (@hobbyquaker),

Thanks for sharing this node!!

On NPM you have both `node-red-contrib-lgtv` and `node-red-contrib-lgtv-with-turnon`.
The links on the NPM page of the latter node, refer to the readme page of the first node.
And they both use the same node ids under the cover, so I can't install them both:
```
12 Sep 08:06:02 - [info] Installing module: node-red-contrib-lgtv, version: 1.1.0
12 Sep 08:08:07 - [info] Installed module: node-red-contrib-lgtv
12 Sep 08:08:08 - [info] Added node types:
12 Sep 08:08:08 - [info]  - node-red-contrib-lgtv:lgtv-config
12 Sep 08:08:08 - [info]  - node-red-contrib-lgtv:lgtv-control
...
12 Sep 08:08:08 - [info] Installing module: node-red-contrib-lgtv-with-turnon, version: 1.0.3
12 Sep 08:08:39 - [info] Installed module: node-red-contrib-lgtv-with-turnon
12 Sep 08:08:39 - [info] Added node types:
12 Sep 08:08:39 - [info]  - node-red-contrib-lgtv-with-turnon:lgtv-config : lgtv-config already registered
12 Sep 08:08:39 - [info]  - node-red-contrib-lgtv-with-turnon:lgtv-control : lgtv-control already registered
...
```
Sorry if this question has already been asked somewhere, but what is the difference between both nodes?
And should I only install the latter one, because it is version ***1.0.3*** while the first one is version ***1.0.0***.

Thanks !!
Bart

**Comment by jeroen13** [comment]
`node-red-contrib-lgtv` is the original version.
`node-red-contrib-lgtv-with-fullscreen` is modded so it can launch the browser in fullscreen modus.
`node-red-contrib-lgtv-with-turnon` probably has a wake-on-lan feature to remotely turn on the TV, but it is nowhere documented on github or something. The npm.js page and readme is the exact same as node-red-contrib-lgtv 

If you are only going to use the features listed by the original `node-red-contrib-lgtv` then your best bet is to install the original.

**Comment by bartbutenaers** [comment]
Ok, thanks for the clarification!
