### ISSUE TITLE
lgtv-app payload options

### ISSUE THREAD

**Issue by robross0606** [hobbyquaker/node-red-contrib-lgtv#3]
Can you tell me how I can figure out the correct msg.payload to launch different apps?  For example, what is the correct payload for Plex?

**Comment by hobbyquaker** [comment]
Just take a look at the output of the app node (connect a debug node) and start plex with your remote, then you should see the payload in the debug tab.

**Comment by robross0606** [comment]
Wow, thanks!  Who would have guessed the payload for Plex is "cdp-30".  O_o
