### ISSUE TITLE
Install fails on RedMatic

### ISSUE THREAD

**Issue by tmoreco** [hobbyquaker/node-red-contrib-lgtv#31]
When trying to install the nodes through the palette manager in RedMatic, install fails repeatedly with the following error:

`gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! fi...`

Running RedMatic 6.0.4 on a Raspberry Pi 3B+ with RaspberryMatic 3.53.30.20200919.

I honestly have no idea what to do about that. Any help would be highly appreciated!

**Comment by UserRG** [comment]
Ich habe das gleiche Problem (wie auch schon bei Harmony-Hub)...
