### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by bolfox** [hobbyquaker/node-red-contrib-lgtv#5]
I have tried with host name and with ip, it keep try connetting without succesfull...

**Comment by hobbyquaker** [comment]
what‘s the exact name of your tv?

**Comment by bolfox** [comment]
UH750V

**Comment by hobbyquaker** [comment]
did you allow "LG Connect Apps"? (see  http://www.lg.com/uk/support/product-help/CT00008334-1437131798537-others)

**Comment by bolfox** [comment]
Yes, with phone app it works, tried also with direct ip address

**Comment by hobbyquaker** [comment]
hmm... then I'm a bit clueless. Can you try (from the machine where node-red is running) to do a `telnet <ip-address> 3000` and check if it can establish a connection?

**Comment by bolfox** [comment]
Yes, connected... i tried also to install lgtv2

**Comment by hobbyquaker** [comment]
and the example from lgtv2 also doesn't work?

**Comment by bolfox** [comment]
After logging with telnet it works, probably because on raspberry there is no telnet, i hd installed to check your question and now works, but with IP, not host name

**Comment by hobbyquaker** [comment]
ok, cool :) so we can close this issue?

**Comment by bolfox** [comment]
Yes
