### ISSUE TITLE
Not able to connect anymore

### ISSUE THREAD

**Issue by pwasem** [hobbyquaker/node-red-contrib-lgtv#8]
Not able to connect to my lgtv any more running firmware 05.80.10.
Config not does not retrieve a token anymore.

**Comment by xRmg** [comment]
I had the same issue all of a sudden.

Steps i've followed to fix it:

* remove lgtv config from node red
* shut down node red

In tv settings -> network -> lgtv apps -> revoke pairings. 

turn of tv, restart tv, restart node red, add config again
